apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  labels:
    app: bankfinance-lbl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankfinance-lbl
  template:
    metadata:
      labels:
        app: bankfinance-lbl
    spec:
      containers:
      - name: banking_container
        image: chandan3461/banking-finance:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: banking-service
  labels:
    app: bankfinance-lbl
spec:
  selector:
    app: bankfinance-lbl
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31050
